services:
  postgres:
    container_name: postgres-vehicle-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DENNIS
      PGDATA: /var/lib/postgresql/data
      POSTGRES-DB: vehicleRentalManagementDB
    volumes:
      - postgres:/data/postgres
    ports:
        - "1090:5432"

    networks:
      - springboot-app
    restart: unless-stopped

networks:
  springboot-app:
    driver: bridge
volumes:
  postgres:
    driver: local




